---
# Installs apache
- name: install apache httpd
  package:
    name: "{{ httpd_packages }}"
    state: present
  register: httpd_install_apache_httpd
  until: httpd_install_apache_httpd is succeeded
  retries: 3

- name: install requirements
  pip:
    name: "{{ httpd_requirements }}"
    state: present
  register: httpd_install_requirements
  until: httpd_install_requirements is succeeded
  retries: 3

- name: create directories for virtual hosts
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ httpd_other_diretories }}"

- name: Change file ownership, group and permissions
  file:
    path: /var/wwww/
    owner: root
    group: root
    mode: 0755
    state: directory