---
# handlers file for httpd
- name: test httpd configuration validity
  command: "{{ httpd_binary }} -t"
  changed_when: no
  retries: 3

- name: restart httpd
  service:
    name: "{{ httpd_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
